### ISSUE TITLE
this doesn't seem right

### ISSUE THREAD

**Issue by rosedemaio** [rosedemaio/lunchbox#9]
![screen shot 2015-04-14 at 9 46 45 pm](https://cloud.githubusercontent.com/assets/3391706/7150892/d23180e0-e2ef-11e4-8402-78523744c0cb.png)

**Comment by rosedemaio** [comment]
routing is totally screwed up

**Comment by tswartz** [comment]
Isn't it still hardcoded to the french onion soup recipe?

**Comment by rosedemaio** [comment]
It's that thing of when you're showing your app to someone late at night and then you're like "WHAT THE HELL IS WRONG WITH THIS" and your only course of action is to open rage issues
